export const TERMINAL_COPY = {
  title: "News Trading Terminal",
  subtitle: "Professional desk for high-impact releases.",
  version: "Version 13.0",
  offline: "Offline — showing cached terminal data.",
  unavailable: "Live data is temporarily unavailable.",
  retry: "Retry",
  top: {
    today: "Today's High Impact",
    upcoming: "Upcoming Event",
    countdown: "Countdown",
    sentiment: "Market Sentiment",
  },
  smart: {
    title: "Smart Dashboard",
    usd: "USD Strength",
    gold: "Gold Bias",
    silver: "Silver Bias",
    crypto: "Crypto Bias",
    indices: "Indices Bias",
  },
  feed: { title: "Live News Feed" },
  playbook: { title: "Trade Playbook" },
  coach: { title: "AI Trading Coach" },
  watchlist: { title: "Watchlist", hint: "News feed updates pinned assets only." },
  heatmap: { title: "Market Heatmap" },
  impact: { title: "News Impact Meter" },
  session: { title: "Session Status" },
  volatility: { title: "Volatility Meter" },
  checklist: { title: "News Checklist" },
  charts: { title: "Desk Charts" },
  preferences: { title: "Preferences" },
  analyze: "Open Analysis",
  calendar: "Calendar",
} as const;
