export const WORKSPACE_COPY = {
  title: "TradeImpact",
  subtitle: "Trader workspace for high-impact releases.",
  version: "Version 13.0",
  offline: "Offline — showing cached workspace data.",
  unavailable: "Live data is temporarily unavailable.",
  retry: "Retry",
  sections: {
    nextNews: "Next High Impact News",
    countdown: "Countdown",
    todaysBias: "Today's Bias",
    watchlist: "Watchlist",
    recent: "Recent Analysis",
    oneClick: "One Click Analysis",
    checklist: "Trade Checklist",
    journal: "Trade Journal",
    favorites: "Favorites",
    search: "Search",
    market: "Market Status",
    notifications: "Notifications",
    settings: "Settings",
  },
  watchlist: {
    hint: "Pin assets — only pinned names appear on the dashboard.",
    empty: "Your watchlist is empty. Pin Gold, Silver, BTC, or EURUSD to start.",
  },
  oneClick: {
    hint: "Tap today's event — biases for your watchlist appear instantly.",
    empty: "No focus event yet. Open Calendar when the next release is listed.",
    confidence: "Confidence",
  },
  journal: {
    empty: "No journal entries yet. Log a trade after your next analysis.",
    add: "Add entry",
    entry: "Entry",
    sl: "SL",
    tp: "TP",
    result: "Result",
    pl: "P/L",
    notes: "Notes",
    save: "Save",
    delete: "Delete",
  },
  favorites: {
    news: "News",
    pairs: "Pairs",
    strategies: "Strategies",
  },
  search: {
    placeholder: "Search Gold, CPI, NFP, BTC, EURUSD…",
    empty: "No matches. Try a pair (EURUSD) or release (CPI, NFP).",
    hint: "Search news, pairs, and workspace shortcuts.",
  },
  market: {
    open: "Market Open",
    closed: "Market Closed",
  },
  notifications: {
    empty: "No notifications yet. Enable prefs in Settings to stay ready.",
    markAll: "Mark all read",
    upcoming: "Upcoming News",
    released: "Released",
    analysisReady: "Analysis Ready",
  },
  settings: {
    theme: "Theme",
    language: "Language",
    defaultPair: "Default Pair",
    defaultNews: "Default News",
    notificationPrefs: "Notification Preferences",
    hint: "Defaults apply to one-click analysis and the Analyze flow.",
  },
  onboarding: {
    title: "Get started",
    body: "Pin a watchlist asset, then open Analyze or tap today’s release for a bias.",
    ctaAnalyze: "Open Analyze",
    ctaCalendar: "Open Calendar",
  },
  recentEmpty: "No recent analysis yet. Run Analyze to populate this list.",
  quick: {
    analyze: "Analyze",
    calendar: "Calendar",
    history: "History",
    journal: "Journal",
  },
  analyze: "Analyze",
  calendar: "Calendar",
  terminal: "Terminal",
} as const;
